#!/bin/zsh

BGreen='\e[1;32m'       # Green
BRed='\e[1;31m'         # Red
Color_Off='\e[0m'       # Text Reset

function setStatusMessage {
    printf "${IRed} --> ${BGreen}$1${Color_Off}\n" 1>&2
}

printf "${BGreen}     .___      __    _____.__.__                  ${Color_Off}\n"
printf "${BGreen}   __| _/_____/  |__/ ____\__|  |   ____   ______ ${Color_Off}\n"
printf "${BGreen}  / __ |/  _ \   __\   __\|  |  | _/ __ \ /  ___/ ${Color_Off}\n"
printf "${BGreen} / /_/ (  <_> )  |  |  |  |  |  |_\  ___/ \___ \  ${Color_Off}\n"
printf "${BGreen} \____ |\____/|__|  |__|  |__|____/\___  >____  > ${Color_Off}\n"
printf "${BGreen}      \/   http://twitter.com/r0derik  \/     \/  ${Color_Off}\n\n"


setStatusMessage "Set MacOS preferences - some settings need a reboot to activate"
./macos

if [[ ! -f "./computers/$1" ]]; then
  ./computers/$1
fi

if [[ `uname -m` == "arm64" ]]; then
  if [[ ! -d "/opt/homebrew" ]]; then
    setStatusMessage "Installing Homebrew (ARM)"
    cd ~
    mkdir homebrew && curl -L https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C homebrew
    sudo mv homebrew /opt/homebrew
    setStatusMessage "Updating Homebrew"
    cd /opt/homebrew/bin
    ./brew update
    cd ~/dotfiles
  fi
fi

if [[ ! -d "/usr/local/Homebrew" ]]; then
  setStatusMessage "Installing Homebrew (Intel)"
  cd ~
  arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
fi

export PATH="/opt/homebrew/bin:$PATH"

setStatusMessage "Installing Homebrew applications from the main Brewfile"
brew bundle
brew cleanup

setStatusMessage "Fixing permissions"
if [[ -d ~/.ssh ]]; then
  find ~/.ssh/ -type f -exec chmod 600 {} \;; find ~/.ssh/ -type d -exec chmod 700 {} \;; find ~/.ssh/ -type f -name "*.pub" -exec chmod 644 {} \;
fi
chmod -R g-w '/usr/local/share/zsh'
chmod go-w '/opt/homebrew/share'


if [[ ! -d ~/Development/bpaas-launchpad ]]; then
  setStatusMessage "Setting up the development environment"
  mkdir -p ~/Development
  cd ~/development
  git clone git@github.com:settlemint/bpaas-launchpad.git
fi

if [[ ! -d ~/.vim ]]; then
  setStatusMessage "Setting up VIM"
  curl -L https://bit.ly/janus-bootstrap | bash
fi

setStatusMessage "Copying the dotfiles to ~"
cp ~/dotfiles/zsh/.* ~;
git config --global user.name "Roderik van der Veer"
git config --global user.email "roderik@settlemint.com"
git config --global init.defaultBranch main