#!/bin/zsh

# Set computer name (as done via System Preferences → Sharing)
sudo scutil --set ComputerName "eris"
sudo scutil --set HostName "eris"
sudo scutil --set LocalHostName "eris"
sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string "eris"
