#!/bin/zsh

# Set computer name (as done via System Preferences → Sharing)
sudo scutil --set ComputerName "nix"
sudo scutil --set HostName "nix"
sudo scutil --set LocalHostName "nix"
sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string "nix"
