command_timeout = 50000
continuation_prompt = '▶▶ '

# A minimal left prompt
format = """$character $directory"""

# move the rest of the prompt to the right
right_format = """$all"""

[kubernetes]
disabled = false
format = 'on [$symbol$context( \($namespace\))]($style) '

[kubernetes.context_aliases]
"dev.local.cluster.k8s" = "dev"
".*/openshift-cluster/.*" = "openshift"
"gke_.*_(?P<cluster>[\\w-]+)" = "gke/$cluster"
"arn:aws:eks:.*/(?P<cluster>[\\w-]+)" = "aws/$cluster"
"aks-(?P<cluster>[\\w-]+)" = "aks/$cluster"
"(?P<cluster>[\\w-]+)/.*/admin" = "ibm/$cluster"

[aws]
disabled = true

[gcloud]
disabled = true

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"

[docker_context]
disabled = true

[directory]
truncation_length = 4
truncation_symbol = '…/'
truncate_to_repo = false